// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNutFactory.Models;

#nullable disable

namespace WebNutFactory.Migrations
{
    [DbContext(typeof(FactoryContext))]
    partial class FactoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoriesStore", b =>
                {
                    b.Property<int>("inventoriesInventoryID")
                        .HasColumnType("int");

                    b.Property<int>("storesStoreID")
                        .HasColumnType("int");

                    b.HasKey("inventoriesInventoryID", "storesStoreID");

                    b.HasIndex(new[] { "storesStoreID" }, "IX_InventoriesStores_storesStoreID");

                    b.ToTable("InventoriesStores", (string)null);
                });

            modelBuilder.Entity("InventoryStore", b =>
                {
                    b.Property<int>("inventoriesInventoryID")
                        .HasColumnType("int");

                    b.Property<int>("storesStoreID")
                        .HasColumnType("int");

                    b.HasKey("inventoriesInventoryID", "storesStoreID");

                    b.ToTable("InventoryStore");
                });

            modelBuilder.Entity("WebNutFactory.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CPassword")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebNutFactory.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex(new[] { "InventoryID" }, "IX_Employees_InventoryID");

                    b.HasIndex(new[] { "StoreID" }, "IX_Employees_StoreID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebNutFactory.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("WebNutFactory.Models.LoginManager", b =>
                {
                    b.Property<int>("LoginManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginManagerID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginManagerID");

                    b.ToTable("LoginManager");
                });

            modelBuilder.Entity("WebNutFactory.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("InvetoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("oStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex(new[] { "CustomerID" }, "IX_Orders_CustomerID");

                    b.HasIndex(new[] { "InvetoryID" }, "IX_Orders_InvetoryID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebNutFactory.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("numProduct")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID")
                        .HasName("PK__OrderDet__08D097C16B34D33C");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebNutFactory.Models.ProductsOfFactory", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("ProductsOfFactory");
                });

            modelBuilder.Entity("WebNutFactory.Models.QuantityProduct", b =>
                {
                    b.Property<int>("QuantityProductsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuantityProductsID"));

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("QuantityProductsID");

                    b.HasIndex(new[] { "InventoryID" }, "IX_QuantityProducts_InventoryID");

                    b.HasIndex(new[] { "ProductID" }, "IX_QuantityProducts_ProductID");

                    b.ToTable("QuantityProducts");
                });

            modelBuilder.Entity("WebNutFactory.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalSuppliedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("InventoriesStore", b =>
                {
                    b.HasOne("WebNutFactory.Models.Inventory", null)
                        .WithMany()
                        .HasForeignKey("inventoriesInventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNutFactory.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("storesStoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebNutFactory.Models.Employee", b =>
                {
                    b.HasOne("WebNutFactory.Models.Inventory", "Inventory")
                        .WithMany("Employees")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNutFactory.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("WebNutFactory.Models.Order", b =>
                {
                    b.HasOne("WebNutFactory.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNutFactory.Models.Inventory", "Invetory")
                        .WithMany("Orders")
                        .HasForeignKey("InvetoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invetory");
                });

            modelBuilder.Entity("WebNutFactory.Models.OrderDetail", b =>
                {
                    b.HasOne("WebNutFactory.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__151B244E");

                    b.HasOne("WebNutFactory.Models.ProductsOfFactory", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Produ__160F4887");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebNutFactory.Models.QuantityProduct", b =>
                {
                    b.HasOne("WebNutFactory.Models.Inventory", "Inventory")
                        .WithMany("QuantityProducts")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNutFactory.Models.ProductsOfFactory", "Product")
                        .WithMany("QuantityProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebNutFactory.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebNutFactory.Models.Inventory", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");

                    b.Navigation("QuantityProducts");
                });

            modelBuilder.Entity("WebNutFactory.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebNutFactory.Models.ProductsOfFactory", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("QuantityProducts");
                });

            modelBuilder.Entity("WebNutFactory.Models.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
