// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

[Index("InventoryID", Name = "IX_Employees_InventoryID")]
[Index("StoreID", Name = "IX_Employees_StoreID")]
public partial class Employee
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    public string FirstName { get; set; }

    [Required]
    public string LastName { get; set; }

    public int InventoryID { get; set; }

    public int StoreID { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Position { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Salary { get; set; }

    [ForeignKey("InventoryID")]
    [InverseProperty("Employees")]
    public virtual Inventory Inventory { get; set; }

    [ForeignKey("StoreID")]
    [InverseProperty("Employees")]
    public virtual Store Store { get; set; }
}