// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

public partial class FactoryContext : DbContext
{
    public FactoryContext()
    {
    }

    public FactoryContext(DbContextOptions<FactoryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<ProductsOfFactory> Ords { get; set; }

    public virtual DbSet<QuantityProduct> QuantityProducts { get; set; }

    public virtual DbSet<LoginManager> LoginManager { get; set; }
    public virtual DbSet<Store> Stores { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

           => optionsBuilder.UseSqlServer("server=DESKTOP-GBV4HIQ;Initial Catalog = NutFactory ;Integrated Security=true; Trust server certificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasMany(d => d.storesStores).WithMany(p => p.inventoriesInventories)
                .UsingEntity<Dictionary<string, object>>(
                    "InventoriesStore",
                    r => r.HasOne<Store>().WithMany().HasForeignKey("storesStoreID"),
                    l => l.HasOne<Inventory>().WithMany().HasForeignKey("inventoriesInventoryID"),
                    j =>
                    {
                        j.HasKey("inventoriesInventoryID", "storesStoreID");
                        j.ToTable("InventoriesStores");
                        j.HasIndex(new[] { "storesStoreID" }, "IX_InventoriesStores_storesStoreID");
                    });
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => new { e.OrderID, e.ProductID }).HasName("PK__OrderDet__08D097C16B34D33C");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails).HasConstraintName("FK__OrderDeta__Order__151B244E");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails).HasConstraintName("FK__OrderDeta__Produ__160F4887");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}