// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

public partial class Inventory
{
    [Key]
    public int InventoryID { get; set; }

    [Required]
    public string Location { get; set; }

    [Required]
    public string Phone { get; set; }

    [InverseProperty("Inventory")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("Invetory")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Inventory")]
    public virtual ICollection<QuantityProduct> QuantityProducts { get; set; } = new List<QuantityProduct>();

    [ForeignKey("inventoriesInventoryID")]
    [InverseProperty("inventoriesInventories")]
    public virtual ICollection<Store> storesStores { get; set; } = new List<Store>();
}