// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

[Index("CustomerID", Name = "IX_Orders_CustomerID")]
[Index("InvetoryID", Name = "IX_Orders_InvetoryID")]
public partial class Order
{
    [Key]
    public int OrderID { get; set; }

    public DateTime orderDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalPrice { get; set; }

    public string oStatus { get; set; }

    public int CustomerID { get; set; }

    public int InvetoryID { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("Orders")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("InvetoryID")]
    [InverseProperty("Orders")]
    public virtual Inventory Invetory { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}