// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

[Table("ProductsOfFactory")]
public partial class ProductsOfFactory
{
    [Key]
    public int ProductID { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public string Manufacturer { get; set; }

    [Required]
    public decimal Price { get; set; }

    [Required]
    public string ProductName { get; set; }

    public int? StockQuantity { get; set; }
    public string ImagePath { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [InverseProperty("Product")]
    public virtual ICollection<QuantityProduct> QuantityProducts { get; set; } = new List<QuantityProduct>();
}