// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

[Index("InventoryID", Name = "IX_QuantityProducts_InventoryID")]
[Index("ProductID", Name = "IX_QuantityProducts_ProductID")]
public partial class QuantityProduct
{
    [Key]
    public int QuantityProductsID { get; set; }

    public int ProductID { get; set; }

    public int InventoryID { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("InventoryID")]
    [InverseProperty("QuantityProducts")]
    public virtual Inventory Inventory { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("QuantityProducts")]
    public virtual ProductsOfFactory Product { get; set; }
}