// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebNutFactory.Models;

public partial class Store
{
    [Key]
    public int StoreID { get; set; }

    public string StoreName { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    public int? NumberOfProducts { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalSuppliedPrice { get; set; }

    [InverseProperty("Store")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("storesStoreID")]
    [InverseProperty("storesStores")]
    public virtual ICollection<Inventory> inventoriesInventories { get; set; } = new List<Inventory>();
}